import Link from "next/link";
import { asc, eq } from "drizzle-orm";
import { notFound, redirect } from "next/navigation";
import { ArrowLeft, Camera, Clock3, Download, MapPin, Plus, Snowflake } from "lucide-react";
import { createProposalAction, reopenWorkOrderAction, scheduleWorkOrderAction, startVisitAction } from "@/app/actions";
import { FormMessage } from "@/components/form-message";
import { StatusBadge } from "@/components/status-badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { NativeSelect, NativeSelectOption } from "@/components/ui/native-select";
import { Textarea } from "@/components/ui/textarea";
import { getDb } from "@/db";
import { clients, documents, locations, machineProposals, machines, users, visits, workOrderMachines, workOrders } from "@/db/schema";
import { requireUser } from "@/lib/auth";
import { canUserAccessWorkOrder, SLOT_LABELS, TYPE_LABELS } from "@/lib/domain";

export default async function WorkOrderPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ error?: string; completed?: string; reopened?: string; proposal?: string; scheduled?: string }> }) {
  const user = await requireUser();
  const { id } = await params;
  const query = await searchParams;
  const db = getDb();
  const context = (await db.select({ order: workOrders, client: clients, location: locations, technician: users }).from(workOrders)
    .innerJoin(clients, eq(workOrders.clientId, clients.id)).innerJoin(locations, eq(workOrders.locationId, locations.id))
    .leftJoin(users, eq(workOrders.assignedTechnicianId, users.id)).where(eq(workOrders.id, id)).limit(1))[0];
  if (!context) notFound();
  const { order, client, location, technician } = context;
  if (!canUserAccessWorkOrder(user.role, user.id, order.assignedTechnicianId)) redirect("/dashboard");
  const [machineRows, visitRows, proposalRows, technicianRows] = await Promise.all([
    db.select({ machine: machines }).from(workOrderMachines).innerJoin(machines, eq(workOrderMachines.machineId, machines.id)).where(eq(workOrderMachines.workOrderId, id)),
    db.select({ visit: visits, technician: users, document: documents }).from(visits).innerJoin(users, eq(visits.technicianId, users.id)).leftJoin(documents, eq(visits.id, documents.visitId)).where(eq(visits.workOrderId, id)).orderBy(asc(visits.sequence)),
    db.select().from(machineProposals).where(eq(machineProposals.workOrderId, id)),
    db.select({ id: users.id, displayName: users.displayName }).from(users).where(eq(users.role, "TECHNICIAN")),
  ]);
  const draft = visitRows.find(({ visit }) => visit.outcome === "DRAFT")?.visit;
  const canStart = user.role === "TECHNICIAN" && !draft && order.status === "ASSIGNED";
  return <main className="app-main">
    <Link href={user.role === "OFFICE" ? "/trabajos" : "/dashboard"} className="mb-4 inline-flex items-center gap-2 text-sm font-semibold text-[#087f86]"><ArrowLeft className="size-4" /> Volver a trabajos</Link>
    <div className="flex flex-wrap items-start justify-between gap-4"><div><p className="eyebrow">{TYPE_LABELS[order.type]}</p><h1 className="page-title">{order.number}</h1><p className="page-subtitle">{client.name} · {location.name}</p></div><StatusBadge status={order.status} /></div>
    <div className="mt-5"><FormMessage error={query.error} success={query.completed ? "La visita se cerró y su PDF ya está disponible." : query.reopened ? "El trabajo se reabrió. La visita anterior y su PDF se conservan." : query.proposal ? "La propuesta se envió a oficina." : query.scheduled ? "La próxima visita quedó programada." : undefined} /></div>
    <div className="mt-6 grid gap-5 xl:grid-cols-[minmax(0,1fr)_320px]">
      <div className="space-y-5"><Card className="gap-4 border-[#d2e2e2] bg-white"><CardHeader><CardTitle>Solicitud</CardTitle></CardHeader><CardContent className="space-y-4"><p className="whitespace-pre-wrap text-base">{order.reportedIssue}</p><div className="grid gap-3 border-t border-slate-100 pt-4 text-sm sm:grid-cols-2"><p><MapPin className="mr-2 inline size-4 text-[#087f86]" />{location.address}</p><p><Clock3 className="mr-2 inline size-4 text-[#087f86]" />{order.scheduledDate ?? "Sin fecha"} · {order.timeSlot ? SLOT_LABELS[order.timeSlot] : "Sin franja"}</p><p><span className="font-semibold">Técnico:</span> {technician?.displayName ?? "Sin asignar"}</p><p><span className="font-semibold">Contacto:</span> {location.contactName || client.contactName || "No indicado"} {location.phone || client.phone}</p></div>{order.officeNotes && <p className="rounded-xl bg-[#f1f8f7] p-3 text-sm"><strong>Indicaciones:</strong> {order.officeNotes}</p>}</CardContent></Card>
      <Card className="gap-4 border-[#d2e2e2] bg-white"><CardHeader><CardTitle>Máquinas del trabajo</CardTitle></CardHeader><CardContent className="space-y-3">{machineRows.map(({ machine }) => <Link key={machine.id} href={`/maquinas/${machine.id}`} className="flex items-center gap-3 rounded-xl border border-[#d2e2e2] p-3 hover:bg-[#f1f8f7]"><span className="grid size-9 place-items-center rounded-lg bg-[#e6f4f3] text-[#087f86]"><Snowflake className="size-5" /></span><span className="min-w-0"><span className="block font-semibold">{machine.code} · {machine.type}</span><span className="block truncate text-sm text-slate-500">{machine.brand} {machine.model} · {machine.internalLocation}</span></span></Link>)}{proposalRows.map((proposal) => <div key={proposal.id} className="rounded-xl border border-dashed border-amber-300 bg-amber-50 p-3 text-sm"><strong>Máquina propuesta:</strong> {proposal.proposedCode} · {proposal.proposedType} <span className="text-amber-800">({proposal.status === "PENDING" ? "Pendiente de revisión" : proposal.status === "APPROVED" ? "Aprobada" : "Rechazada"})</span></div>)}</CardContent></Card>
      <Card className="gap-4 border-[#d2e2e2] bg-white"><CardHeader><CardTitle>Visitas y partes</CardTitle></CardHeader><CardContent>{visitRows.length ? <div className="space-y-4">{visitRows.map(({ visit, technician: visitTechnician, document }) => <div key={visit.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-[#d2e2e2] p-4"><div><p className="font-semibold">Visita {visit.sequence} · {visitTechnician.displayName}</p><p className="text-sm text-slate-500">{visit.scheduledDate ?? "Sin fecha prevista"} · {visit.timeSlot ? SLOT_LABELS[visit.timeSlot] : "Sin franja"} · {visit.startedAt ? new Date(visit.startedAt).toLocaleString("es-PE") : "No iniciada"} · {visit.outcome === "DRAFT" ? "En curso" : visit.outcome === "COMPLETED" ? "Terminada" : visit.outcome === "PENDING_PART" ? "Pendiente de pieza" : "Pendiente de volver"}</p></div><div className="flex gap-2">{visit.outcome === "DRAFT" && user.role === "TECHNICIAN" && <Button asChild><Link href={`/trabajos/${id}/visitas/${visit.id}`}>Rellenar parte</Link></Button>}{document && <Button variant="outline" asChild><a href={`/archivos/documento/${document.id}`}><Download /> PDF</a></Button>}</div></div>)}</div> : <p className="text-sm text-slate-500">Todavía no hay visitas registradas.</p>}</CardContent></Card></div>
      <div className="space-y-5">{canStart && <Card className="gap-4 border-[#a8d4d1] bg-[#e6f4f3]"><CardHeader><CardTitle>Iniciar visita</CardTitle></CardHeader><CardContent><p className="mb-4 text-sm text-slate-600">Se registrará la hora de inicio y podrás completar el parte.</p><form action={startVisitAction}><input type="hidden" name="workOrderId" value={id} /><Button type="submit" className="h-11 w-full bg-[#087f86] hover:bg-[#076970]"><Plus /> Iniciar trabajo</Button></form></CardContent></Card>}
        {user.role === "OFFICE" && ["REGISTERED", "ASSIGNED", "PENDING_PART", "PENDING_RETURN"].includes(order.status) && <Card className="gap-4 border-[#d2e2e2] bg-white"><CardHeader><CardTitle>{order.status === "PENDING_PART" || order.status === "PENDING_RETURN" ? "Programar próxima visita" : "Asignar visita"}</CardTitle></CardHeader><CardContent><form action={scheduleWorkOrderAction} className="space-y-3"><input type="hidden" name="workOrderId" value={id} /><div><Label htmlFor="technicianId">Técnico</Label><NativeSelect id="technicianId" name="technicianId" defaultValue={order.assignedTechnicianId ?? undefined} className="h-11 w-full" required><NativeSelectOption value="">Seleccionar</NativeSelectOption>{technicianRows.map((person) => <NativeSelectOption key={person.id} value={person.id}>{person.displayName}</NativeSelectOption>)}</NativeSelect></div><div><Label htmlFor="scheduledDate">Fecha</Label><Input id="scheduledDate" name="scheduledDate" type="date" defaultValue={order.scheduledDate ?? ""} className="h-11" required /></div><div><Label htmlFor="timeSlot">Franja</Label><NativeSelect id="timeSlot" name="timeSlot" defaultValue={order.timeSlot ?? "MORNING"} className="h-11 w-full"><NativeSelectOption value="MORNING">Mañana</NativeSelectOption><NativeSelectOption value="AFTERNOON">Tarde</NativeSelectOption></NativeSelect></div><Button type="submit" className="h-11 w-full bg-[#087f86] hover:bg-[#076970]">Guardar asignación</Button></form></CardContent></Card>}
        {user.role === "OFFICE" && order.status === "COMPLETED" && <Card className="gap-4 border-[#d2e2e2] bg-white"><CardHeader><CardTitle>Reabrir trabajo</CardTitle></CardHeader><CardContent><form action={reopenWorkOrderAction} className="space-y-3"><input type="hidden" name="workOrderId" value={id} /><Label htmlFor="reason">Motivo de la reapertura</Label><Textarea id="reason" name="reason" required /><Button type="submit" variant="outline">Reabrir y conservar parte anterior</Button></form></CardContent></Card>}
        {user.role === "TECHNICIAN" && order.status !== "COMPLETED" && <Card className="gap-4 border-[#d2e2e2] bg-white"><CardHeader><CardTitle>¿Falta una máquina?</CardTitle></CardHeader><CardContent><form action={createProposalAction} className="space-y-3"><input type="hidden" name="workOrderId" value={id} /><div className="grid grid-cols-2 gap-3"><div><Label htmlFor="code">Código</Label><Input id="code" name="code" required /></div><div><Label htmlFor="type">Tipo</Label><Input id="type" name="type" required /></div></div><div><Label htmlFor="brand">Marca</Label><Input id="brand" name="brand" /></div><div><Label htmlFor="model">Modelo</Label><Input id="model" name="model" /></div><div><Label htmlFor="serialNumber">Serie</Label><Input id="serialNumber" name="serialNumber" /></div><div><Label htmlFor="internalLocation">Ubicación dentro del local</Label><Input id="internalLocation" name="internalLocation" /></div><div><Label htmlFor="proposalPhoto">Foto</Label><Input id="proposalPhoto" name="photo" type="file" accept="image/jpeg,image/png,image/webp" /></div><Button type="submit" variant="outline" className="w-full"><Camera /> Proponer alta</Button></form></CardContent></Card>}
      </div>
    </div>
  </main>;
}
